# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qleetpctl < Formula
  desc "A CLI for managing the Qleet OS."
  homepage "https://github.com/qleet/qleetctl"
  version "0.1.1"
  license "MIT"

  depends_on "kubectl"
  depends_on "kind"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.1/qleetctl_v0.1.1_macOS_arm64.tar.gz"
      sha256 "e23f7f65b481f8b20cfd87280b1c2b5d266698a177ee6459ebc02533e8a36c2d"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.1/qleetctl_v0.1.1_macOS_x86_64.tar.gz"
      sha256 "2d8f95ab3acedf87b6b900c07a0d93347d10f98e03ae7466552fff0339c85378"

      def install
        bin.install "qleetctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.1/qleetctl_v0.1.1_Linux_arm.tar.gz"
      sha256 "8b80cdc41d82967b4b23c560ab0916dd3f71403f19fba19029b854a07660caa9"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.1/qleetctl_v0.1.1_Linux_arm64.tar.gz"
      sha256 "dac04eb28b638c7e5a563b92b9b5a8800856be207c2ec97fb52f6db18b22449a"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.1/qleetctl_v0.1.1_Linux_x86_64.tar.gz"
      sha256 "5cc84c9bf4fe4a537e185657ba0a582a23653c25c4dd14be491e09c73e1aefd2"

      def install
        bin.install "qleetctl"
      end
    end
  end

  test do
    system "#{bin}/qleetctl version"
  end
end
