# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qleetctl < Formula
  desc "A CLI for managing the Qleet OS."
  homepage "https://github.com/qleet/qleetctl"
  version "0.1.9"
  license "MIT"

  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.9/qleetctl_v0.1.9_Darwin_arm64.tar.gz"
      sha256 "8c301a9be62e902a63af43c8bfb4371f719ae4162ed6d59500a918002c9100fe"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.9/qleetctl_v0.1.9_Darwin_x86_64.tar.gz"
      sha256 "af9df8c4961af543aa7bb2617bb2470f3e7eeefccd17549440aed5f989d02dc7"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.9/qleetctl_v0.1.9_Linux_arm.tar.gz"
      sha256 "e5a4cfc723ba055c386f06d3f26245ff2cebffce6d5a259100598dd5f9b877e7"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.9/qleetctl_v0.1.9_Linux_arm64.tar.gz"
      sha256 "4fb4784ed5cca553ee989da5ed2f4cd9843dfa0a698b59e1d915adbb5e451719"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.9/qleetctl_v0.1.9_Linux_x86_64.tar.gz"
      sha256 "3af25e7b10249d2eb6bcda726501103dd54405c1fefce13fa30e9a4a811dde14"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  test do
    system "#{bin}/qleetctl version"
  end
end
