# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qleetctl < Formula
  desc "A CLI for managing the Qleet OS."
  homepage "https://github.com/qleet/qleetctl"
  version "0.2.1"
  license "MIT"

  depends_on "docker"
  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.1/qleetctl_v0.2.1_Darwin_arm64.tar.gz"
      sha256 "b7481e1ec3f730085876014de657c3878a44be9233e87692e550da46d2644199"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.1/qleetctl_v0.2.1_Darwin_x86_64.tar.gz"
      sha256 "932889cf61823f40f0c39e2ea8dab59576ea1e9027f9f4315710a089dbc34aa7"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.1/qleetctl_v0.2.1_Linux_x86_64.tar.gz"
      sha256 "98e8ac939af4ab8c7ade117a8a77011e5b8c711d3dab0219b3fc2057ff53aaa3"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.1/qleetctl_v0.2.1_Linux_arm.tar.gz"
      sha256 "8aedc380ffc4c044288f7b59f4f7b1fdb0d5070a05788813c74b1710a8f0ccff"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.1/qleetctl_v0.2.1_Linux_arm64.tar.gz"
      sha256 "e17f22b234214bd9bd8b24f1eb99a6fed1466ddaddaa6a09b633354120224761"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  test do
    system "#{bin}/qleetctl version"
  end
end
