# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qleetpctl < Formula
  desc "A CLI for managing the Qleet OS."
  homepage "https://github.com/qleet/qleetctl"
  version "0.1.0"
  license "MIT"

  depends_on "kubectl"
  depends_on "kind"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.0/qleetctl_v0.1.0_macOS_arm64.tar.gz"
      sha256 "4ff6b46d50d6b9f624572aa62d8dcfef1be153e57565e0c4d01c3ccff8741429"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.0/qleetctl_v0.1.0_macOS_x86_64.tar.gz"
      sha256 "652cc299c02f39d478e976faccd3bd30bebd1d24c1c10e25f219206c3404a7ae"

      def install
        bin.install "qleetctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.0/qleetctl_v0.1.0_Linux_x86_64.tar.gz"
      sha256 "7d5d4b002e7866e970f5224f0d446114ce94e7d487c1cff53cf36e5b91d9ce8d"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.0/qleetctl_v0.1.0_Linux_arm.tar.gz"
      sha256 "a74f91d0a50887b165221d31b8d9a1f842f0009e16c0d7fb0618b937b0454489"

      def install
        bin.install "qleetctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.1.0/qleetctl_v0.1.0_Linux_arm64.tar.gz"
      sha256 "900eb8763862a6253fcf0add67712cb73e824d1bf4a051c35c648a0088751ded"

      def install
        bin.install "qleetctl"
      end
    end
  end

  test do
    system "#{bin}/qleetctl version"
  end
end
