# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qleetctl < Formula
  desc "A CLI for managing the Qleet OS."
  homepage "https://github.com/qleet/qleetctl"
  version "0.2.0"
  license "MIT"

  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.0/qleetctl_v0.2.0_Darwin_arm64.tar.gz"
      sha256 "aaa18d2cc27a92f737486ff25d3a34991a95e4775b63fe3a91f3b8f637e44e23"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.0/qleetctl_v0.2.0_Darwin_x86_64.tar.gz"
      sha256 "ebaa89033f1252e6ee4f197a598a2529e292136e103e692234374f7bffb358e4"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.0/qleetctl_v0.2.0_Linux_x86_64.tar.gz"
      sha256 "75c1f498c7a0f93fb2c4c6d6e652166d7cb847452547b0b98031124e2f2a008d"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.0/qleetctl_v0.2.0_Linux_arm.tar.gz"
      sha256 "4864473171a0ed1b4691f99ef04ce24ebbd238dd0e1056e3b0e7b50a680f062d"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qleet/qleetctl/releases/download/v0.2.0/qleetctl_v0.2.0_Linux_arm64.tar.gz"
      sha256 "262973a759f83d9d3d212b518c54c6b29c6e92dfd34c5008a611a497643b24db"

      def install
        bin.install "qleetctl"
        bash_completion.install "completions/qleetctl.bash" => "qleetctl"
        zsh_completion.install "completions/qleetctl.zsh" => "_qleetctl"
        fish_completion.install "completions/qleetctl.fish"
      end
    end
  end

  test do
    system "#{bin}/qleetctl version"
  end
end
